name: CTF-Outside

on:
  push:
    paths:
      - outside.map
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Cache ericw-tools
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: |
            bin/qbsp
            bin/vis
            bin/light
          key: ericw-tools

      - name: Fetch ericw-tools
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          repository: ericwa/ericw-tools
          submodules: true
          path: ericw-tools
        if: steps.cache-dependencies.outputs.cache-hit != 'true'

      - name: Install embree & tbb
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq libembree3-3 libtbb12

      - name: Build ericw-tools
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq libembree-dev libtbb-dev groff
          cd ericw-tools
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make
          mkdir ../../bin
          mv qbsp/qbsp   \
             vis/vis     \
             light/light \
             ../../bin/
        if: steps.cache-dependencies.outputs.cache-hit != 'true'

      - name: Cache wads
        uses: actions/cache@v3
        id: cache-wads
        with:
          path: |
            wads/misc.wad
            wads/liquids.wad
            wads/makkon_stone/makkon_stone.wad
            wads/makkon_nature/makkon_nature.wad
            wads/makkon_building/makkon_building.wad
          key: wads

      - name: Fetch wads
        run: |
          mkdir wads

          curl -s -o quake.zip 'https://valvedev.info/tools/quake-wad-overhaul-project/quake_overhaul_wads.zip'
          unzip -d wads quake.zip misc.wad

          curl -s -o liquids.zip 'https://www.quaddicted.com/files/wads/liquids.zip'
          unzip -d wads liquids.zip liquids.wad

          mkdir wads/makkon_building
          curl -s -o building.zip 'https://www.slipseer.com/index.php?resources/makkon-textures.28/version/117/download&file=931'
          unzip -d wads/makkon_building building.zip makkon_building.wad

          mkdir wads/makkon_nature
          curl -s -o nature.zip 'https://www.slipseer.com/index.php?resources/makkon-textures.28/version/117/download&file=936'
          unzip -d wads/makkon_nature nature.zip makkon_nature.wad

          mkdir wads/makkon_stone
          curl -s -o stone.zip 'https://www.slipseer.com/index.php?resources/makkon-textures.28/version/117/download&file=938'
          unzip -d wads/makkon_stone stone.zip makkon_stone.wad
        if: steps.cache-wads.outputs.cache-hit != 'true'

      - name: Compile map
        run: |
          bin/qbsp -nopercent -splitturb -bsp2 outside.map outside.bsp

      - name: Vis map
        run: |
          bin/vis outside.bsp

      - name: Light map
        run: |
          bin/light -extra4 -soft 4 outside.bsp

      - uses: actions/upload-artifact@v3
        with:
          name: ctf-outside
          path: |
            outside.bsp
            outside.lit
